//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3623
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ProfileServiceBinding", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class ProfileService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getTerminateProfileOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUserProfileOperationCompleted;
    
    private System.Threading.SendOrPostCallback memberChangeAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback memberChangePasswordOperationCompleted;
    
    private System.Threading.SendOrPostCallback memberResetPasswordOperationCompleted;
    
    private System.Threading.SendOrPostCallback setContractEMailOperationCompleted;
    
    private System.Threading.SendOrPostCallback setReadAgreementOperationCompleted;
    
    private System.Threading.SendOrPostCallback subscriberChangePasswordOperationCompleted;
    
    private System.Threading.SendOrPostCallback subscriberResetPasswordOperationCompleted;
    
    /// <remarks/>
    public ProfileService() {
        this.Url = "http://210.200.64.22:8000/profile-service/ProfileService";
    }
    
    /// <remarks/>
    public event getTerminateProfileCompletedEventHandler getTerminateProfileCompleted;
    
    /// <remarks/>
    public event getUserProfileCompletedEventHandler getUserProfileCompleted;
    
    /// <remarks/>
    public event memberChangeAccountCompletedEventHandler memberChangeAccountCompleted;
    
    /// <remarks/>
    public event memberChangePasswordCompletedEventHandler memberChangePasswordCompleted;
    
    /// <remarks/>
    public event memberResetPasswordCompletedEventHandler memberResetPasswordCompleted;
    
    /// <remarks/>
    public event setContractEMailCompletedEventHandler setContractEMailCompleted;
    
    /// <remarks/>
    public event setReadAgreementCompletedEventHandler setReadAgreementCompleted;
    
    /// <remarks/>
    public event subscriberChangePasswordCompletedEventHandler subscriberChangePasswordCompleted;
    
    /// <remarks/>
    public event subscriberResetPasswordCompletedEventHandler subscriberResetPasswordCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("getTerminateProfileResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public getTerminateProfileResponse getTerminateProfile([System.Xml.Serialization.XmlElementAttribute("getTerminateProfile", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] getTerminateProfile getTerminateProfile1) {
        object[] results = this.Invoke("getTerminateProfile", new object[] {
                    getTerminateProfile1});
        return ((getTerminateProfileResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTerminateProfile(getTerminateProfile getTerminateProfile1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTerminateProfile", new object[] {
                    getTerminateProfile1}, callback, asyncState);
    }
    
    /// <remarks/>
    public getTerminateProfileResponse EndgetTerminateProfile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getTerminateProfileResponse)(results[0]));
    }
    
    /// <remarks/>
    public void getTerminateProfileAsync(getTerminateProfile getTerminateProfile1) {
        this.getTerminateProfileAsync(getTerminateProfile1, null);
    }
    
    /// <remarks/>
    public void getTerminateProfileAsync(getTerminateProfile getTerminateProfile1, object userState) {
        if ((this.getTerminateProfileOperationCompleted == null)) {
            this.getTerminateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTerminateProfileOperationCompleted);
        }
        this.InvokeAsync("getTerminateProfile", new object[] {
                    getTerminateProfile1}, this.getTerminateProfileOperationCompleted, userState);
    }
    
    private void OngetTerminateProfileOperationCompleted(object arg) {
        if ((this.getTerminateProfileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTerminateProfileCompleted(this, new getTerminateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("getUserProfileResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public getUserProfileResponse getUserProfile([System.Xml.Serialization.XmlElementAttribute("getUserProfile", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] getUserProfile getUserProfile1) {
        object[] results = this.Invoke("getUserProfile", new object[] {
                    getUserProfile1});
        return ((getUserProfileResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUserProfile(getUserProfile getUserProfile1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUserProfile", new object[] {
                    getUserProfile1}, callback, asyncState);
    }
    
    /// <remarks/>
    public getUserProfileResponse EndgetUserProfile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getUserProfileResponse)(results[0]));
    }
    
    /// <remarks/>
    public void getUserProfileAsync(getUserProfile getUserProfile1) {
        this.getUserProfileAsync(getUserProfile1, null);
    }
    
    /// <remarks/>
    public void getUserProfileAsync(getUserProfile getUserProfile1, object userState) {
        if ((this.getUserProfileOperationCompleted == null)) {
            this.getUserProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserProfileOperationCompleted);
        }
        this.InvokeAsync("getUserProfile", new object[] {
                    getUserProfile1}, this.getUserProfileOperationCompleted, userState);
    }
    
    private void OngetUserProfileOperationCompleted(object arg) {
        if ((this.getUserProfileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUserProfileCompleted(this, new getUserProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("memberChangeAccountResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public memberChangeAccountResponse memberChangeAccount([System.Xml.Serialization.XmlElementAttribute("memberChangeAccount", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] memberChangeAccount memberChangeAccount1) {
        object[] results = this.Invoke("memberChangeAccount", new object[] {
                    memberChangeAccount1});
        return ((memberChangeAccountResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmemberChangeAccount(memberChangeAccount memberChangeAccount1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("memberChangeAccount", new object[] {
                    memberChangeAccount1}, callback, asyncState);
    }
    
    /// <remarks/>
    public memberChangeAccountResponse EndmemberChangeAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((memberChangeAccountResponse)(results[0]));
    }
    
    /// <remarks/>
    public void memberChangeAccountAsync(memberChangeAccount memberChangeAccount1) {
        this.memberChangeAccountAsync(memberChangeAccount1, null);
    }
    
    /// <remarks/>
    public void memberChangeAccountAsync(memberChangeAccount memberChangeAccount1, object userState) {
        if ((this.memberChangeAccountOperationCompleted == null)) {
            this.memberChangeAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmemberChangeAccountOperationCompleted);
        }
        this.InvokeAsync("memberChangeAccount", new object[] {
                    memberChangeAccount1}, this.memberChangeAccountOperationCompleted, userState);
    }
    
    private void OnmemberChangeAccountOperationCompleted(object arg) {
        if ((this.memberChangeAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.memberChangeAccountCompleted(this, new memberChangeAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("memberChangePasswordResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public memberChangePasswordResponse memberChangePassword([System.Xml.Serialization.XmlElementAttribute("memberChangePassword", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] memberChangePassword memberChangePassword1) {
        object[] results = this.Invoke("memberChangePassword", new object[] {
                    memberChangePassword1});
        return ((memberChangePasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmemberChangePassword(memberChangePassword memberChangePassword1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("memberChangePassword", new object[] {
                    memberChangePassword1}, callback, asyncState);
    }
    
    /// <remarks/>
    public memberChangePasswordResponse EndmemberChangePassword(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((memberChangePasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public void memberChangePasswordAsync(memberChangePassword memberChangePassword1) {
        this.memberChangePasswordAsync(memberChangePassword1, null);
    }
    
    /// <remarks/>
    public void memberChangePasswordAsync(memberChangePassword memberChangePassword1, object userState) {
        if ((this.memberChangePasswordOperationCompleted == null)) {
            this.memberChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmemberChangePasswordOperationCompleted);
        }
        this.InvokeAsync("memberChangePassword", new object[] {
                    memberChangePassword1}, this.memberChangePasswordOperationCompleted, userState);
    }
    
    private void OnmemberChangePasswordOperationCompleted(object arg) {
        if ((this.memberChangePasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.memberChangePasswordCompleted(this, new memberChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("memberResetPasswordResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public memberResetPasswordResponse memberResetPassword([System.Xml.Serialization.XmlElementAttribute("memberResetPassword", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] memberResetPassword memberResetPassword1) {
        object[] results = this.Invoke("memberResetPassword", new object[] {
                    memberResetPassword1});
        return ((memberResetPasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmemberResetPassword(memberResetPassword memberResetPassword1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("memberResetPassword", new object[] {
                    memberResetPassword1}, callback, asyncState);
    }
    
    /// <remarks/>
    public memberResetPasswordResponse EndmemberResetPassword(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((memberResetPasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public void memberResetPasswordAsync(memberResetPassword memberResetPassword1) {
        this.memberResetPasswordAsync(memberResetPassword1, null);
    }
    
    /// <remarks/>
    public void memberResetPasswordAsync(memberResetPassword memberResetPassword1, object userState) {
        if ((this.memberResetPasswordOperationCompleted == null)) {
            this.memberResetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmemberResetPasswordOperationCompleted);
        }
        this.InvokeAsync("memberResetPassword", new object[] {
                    memberResetPassword1}, this.memberResetPasswordOperationCompleted, userState);
    }
    
    private void OnmemberResetPasswordOperationCompleted(object arg) {
        if ((this.memberResetPasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.memberResetPasswordCompleted(this, new memberResetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("setContractEMailResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public setContractEMailResponse setContractEMail([System.Xml.Serialization.XmlElementAttribute("setContractEMail", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] setContractEMail setContractEMail1) {
        object[] results = this.Invoke("setContractEMail", new object[] {
                    setContractEMail1});
        return ((setContractEMailResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetContractEMail(setContractEMail setContractEMail1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setContractEMail", new object[] {
                    setContractEMail1}, callback, asyncState);
    }
    
    /// <remarks/>
    public setContractEMailResponse EndsetContractEMail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((setContractEMailResponse)(results[0]));
    }
    
    /// <remarks/>
    public void setContractEMailAsync(setContractEMail setContractEMail1) {
        this.setContractEMailAsync(setContractEMail1, null);
    }
    
    /// <remarks/>
    public void setContractEMailAsync(setContractEMail setContractEMail1, object userState) {
        if ((this.setContractEMailOperationCompleted == null)) {
            this.setContractEMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetContractEMailOperationCompleted);
        }
        this.InvokeAsync("setContractEMail", new object[] {
                    setContractEMail1}, this.setContractEMailOperationCompleted, userState);
    }
    
    private void OnsetContractEMailOperationCompleted(object arg) {
        if ((this.setContractEMailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setContractEMailCompleted(this, new setContractEMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("setReadAgreementResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public setReadAgreementResponse setReadAgreement([System.Xml.Serialization.XmlElementAttribute("setReadAgreement", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] setReadAgreement setReadAgreement1) {
        object[] results = this.Invoke("setReadAgreement", new object[] {
                    setReadAgreement1});
        return ((setReadAgreementResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetReadAgreement(setReadAgreement setReadAgreement1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setReadAgreement", new object[] {
                    setReadAgreement1}, callback, asyncState);
    }
    
    /// <remarks/>
    public setReadAgreementResponse EndsetReadAgreement(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((setReadAgreementResponse)(results[0]));
    }
    
    /// <remarks/>
    public void setReadAgreementAsync(setReadAgreement setReadAgreement1) {
        this.setReadAgreementAsync(setReadAgreement1, null);
    }
    
    /// <remarks/>
    public void setReadAgreementAsync(setReadAgreement setReadAgreement1, object userState) {
        if ((this.setReadAgreementOperationCompleted == null)) {
            this.setReadAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetReadAgreementOperationCompleted);
        }
        this.InvokeAsync("setReadAgreement", new object[] {
                    setReadAgreement1}, this.setReadAgreementOperationCompleted, userState);
    }
    
    private void OnsetReadAgreementOperationCompleted(object arg) {
        if ((this.setReadAgreementCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setReadAgreementCompleted(this, new setReadAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("subscriberChangePasswordResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public subscriberChangePasswordResponse subscriberChangePassword([System.Xml.Serialization.XmlElementAttribute("subscriberChangePassword", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] subscriberChangePassword subscriberChangePassword1) {
        object[] results = this.Invoke("subscriberChangePassword", new object[] {
                    subscriberChangePassword1});
        return ((subscriberChangePasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsubscriberChangePassword(subscriberChangePassword subscriberChangePassword1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("subscriberChangePassword", new object[] {
                    subscriberChangePassword1}, callback, asyncState);
    }
    
    /// <remarks/>
    public subscriberChangePasswordResponse EndsubscriberChangePassword(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((subscriberChangePasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public void subscriberChangePasswordAsync(subscriberChangePassword subscriberChangePassword1) {
        this.subscriberChangePasswordAsync(subscriberChangePassword1, null);
    }
    
    /// <remarks/>
    public void subscriberChangePasswordAsync(subscriberChangePassword subscriberChangePassword1, object userState) {
        if ((this.subscriberChangePasswordOperationCompleted == null)) {
            this.subscriberChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubscriberChangePasswordOperationCompleted);
        }
        this.InvokeAsync("subscriberChangePassword", new object[] {
                    subscriberChangePassword1}, this.subscriberChangePasswordOperationCompleted, userState);
    }
    
    private void OnsubscriberChangePasswordOperationCompleted(object arg) {
        if ((this.subscriberChangePasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.subscriberChangePasswordCompleted(this, new subscriberChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("subscriberResetPasswordResponse", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
    public subscriberResetPasswordResponse subscriberResetPassword([System.Xml.Serialization.XmlElementAttribute("subscriberResetPassword", Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")] subscriberResetPassword subscriberResetPassword1) {
        object[] results = this.Invoke("subscriberResetPassword", new object[] {
                    subscriberResetPassword1});
        return ((subscriberResetPasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsubscriberResetPassword(subscriberResetPassword subscriberResetPassword1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("subscriberResetPassword", new object[] {
                    subscriberResetPassword1}, callback, asyncState);
    }
    
    /// <remarks/>
    public subscriberResetPasswordResponse EndsubscriberResetPassword(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((subscriberResetPasswordResponse)(results[0]));
    }
    
    /// <remarks/>
    public void subscriberResetPasswordAsync(subscriberResetPassword subscriberResetPassword1) {
        this.subscriberResetPasswordAsync(subscriberResetPassword1, null);
    }
    
    /// <remarks/>
    public void subscriberResetPasswordAsync(subscriberResetPassword subscriberResetPassword1, object userState) {
        if ((this.subscriberResetPasswordOperationCompleted == null)) {
            this.subscriberResetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubscriberResetPasswordOperationCompleted);
        }
        this.InvokeAsync("subscriberResetPassword", new object[] {
                    subscriberResetPassword1}, this.subscriberResetPasswordOperationCompleted, userState);
    }
    
    private void OnsubscriberResetPasswordOperationCompleted(object arg) {
        if ((this.subscriberResetPasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.subscriberResetPasswordCompleted(this, new subscriberResetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class getTerminateProfile {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string userIDField;
    
    private string contractIDField;
    
    private string mdnField;
    
    private string minField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractID {
        get {
            return this.contractIDField;
        }
        set {
            this.contractIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mdn {
        get {
            return this.mdnField;
        }
        set {
            this.mdnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class subscriberResetPasswordResponse {
    
    private response returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class response {
    
    private string descriptionField;
    
    private profile profileField;
    
    private string resultCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public profile profile {
        get {
            return this.profileField;
        }
        set {
            this.profileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string resultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class profile {
    
    private acceptance acceptEpaperField;
    
    private bool acceptEpaperFieldSpecified;
    
    private string addressField;
    
    private string bcField;
    
    private string birthdayField;
    
    private string bscsCOIDField;
    
    private string bscsCSCODEField;
    
    private string companyNameField;
    
    private string contactPhoneField;
    
    private string contractIDField;
    
    private yesNoOption contractStatusField;
    
    private bool contractStatusFieldSpecified;
    
    private string contractStatusCodeField;
    
    private string customerIDField;
    
    private string disableWebField;
    
    private string educationField;
    
    private string emailField;
    
    private string enameField;
    
    private gender genderField;
    
    private bool genderFieldSpecified;
    
    private yesNoOption isAdultField;
    
    private bool isAdultFieldSpecified;
    
    private string jobTitleField;
    
    private string mdnField;
    
    private string minField;
    
    private string mobile1Field;
    
    private string mobile2Field;
    
    private string mobilePhoneTypeField;
    
    private string nameField;
    
    private string nicknameField;
    
    private string occupationField;
    
    private string otpStatusField;
    
    private string personalIDField;
    
    private string productTypeField;
    
    private string pushMailField;
    
    private string smscMailField;
    
    private string telphone1Field;
    
    private string telphone2Field;
    
    private string terminateTypeField;
    
    private string uidField;
    
    private string userTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public acceptance acceptEpaper {
        get {
            return this.acceptEpaperField;
        }
        set {
            this.acceptEpaperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool acceptEpaperSpecified {
        get {
            return this.acceptEpaperFieldSpecified;
        }
        set {
            this.acceptEpaperFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bc {
        get {
            return this.bcField;
        }
        set {
            this.bcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string birthday {
        get {
            return this.birthdayField;
        }
        set {
            this.birthdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bscsCOID {
        get {
            return this.bscsCOIDField;
        }
        set {
            this.bscsCOIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bscsCSCODE {
        get {
            return this.bscsCSCODEField;
        }
        set {
            this.bscsCSCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string companyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractID {
        get {
            return this.contractIDField;
        }
        set {
            this.contractIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public yesNoOption contractStatus {
        get {
            return this.contractStatusField;
        }
        set {
            this.contractStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contractStatusSpecified {
        get {
            return this.contractStatusFieldSpecified;
        }
        set {
            this.contractStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractStatusCode {
        get {
            return this.contractStatusCodeField;
        }
        set {
            this.contractStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerID {
        get {
            return this.customerIDField;
        }
        set {
            this.customerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string disableWeb {
        get {
            return this.disableWebField;
        }
        set {
            this.disableWebField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string education {
        get {
            return this.educationField;
        }
        set {
            this.educationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ename {
        get {
            return this.enameField;
        }
        set {
            this.enameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gender gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool genderSpecified {
        get {
            return this.genderFieldSpecified;
        }
        set {
            this.genderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public yesNoOption isAdult {
        get {
            return this.isAdultField;
        }
        set {
            this.isAdultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isAdultSpecified {
        get {
            return this.isAdultFieldSpecified;
        }
        set {
            this.isAdultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string jobTitle {
        get {
            return this.jobTitleField;
        }
        set {
            this.jobTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mdn {
        get {
            return this.mdnField;
        }
        set {
            this.mdnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mobile1 {
        get {
            return this.mobile1Field;
        }
        set {
            this.mobile1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mobile2 {
        get {
            return this.mobile2Field;
        }
        set {
            this.mobile2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mobilePhoneType {
        get {
            return this.mobilePhoneTypeField;
        }
        set {
            this.mobilePhoneTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nickname {
        get {
            return this.nicknameField;
        }
        set {
            this.nicknameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string occupation {
        get {
            return this.occupationField;
        }
        set {
            this.occupationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string otpStatus {
        get {
            return this.otpStatusField;
        }
        set {
            this.otpStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string personalID {
        get {
            return this.personalIDField;
        }
        set {
            this.personalIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productType {
        get {
            return this.productTypeField;
        }
        set {
            this.productTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pushMail {
        get {
            return this.pushMailField;
        }
        set {
            this.pushMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string smscMail {
        get {
            return this.smscMailField;
        }
        set {
            this.smscMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string telphone1 {
        get {
            return this.telphone1Field;
        }
        set {
            this.telphone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string telphone2 {
        get {
            return this.telphone2Field;
        }
        set {
            this.telphone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string terminateType {
        get {
            return this.terminateTypeField;
        }
        set {
            this.terminateTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userType {
        get {
            return this.userTypeField;
        }
        set {
            this.userTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public enum acceptance {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public enum yesNoOption {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public enum gender {
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    F,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class subscriberResetPassword {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string mDNField;
    
    private string personIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MDN {
        get {
            return this.mDNField;
        }
        set {
            this.mDNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string personID {
        get {
            return this.personIDField;
        }
        set {
            this.personIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class subscriberChangePasswordResponse {
    
    private response returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class subscriberChangePassword {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string mDNField;
    
    private string oldPasswordField;
    
    private string newPasswordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MDN {
        get {
            return this.mDNField;
        }
        set {
            this.mDNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string oldPassword {
        get {
            return this.oldPasswordField;
        }
        set {
            this.oldPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string newPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class setReadAgreementResponse {
    
    private response responseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class setReadAgreement {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string userIDField;
    
    private string contractIDField;
    
    private string mdnField;
    
    private string minField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractID {
        get {
            return this.contractIDField;
        }
        set {
            this.contractIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mdn {
        get {
            return this.mdnField;
        }
        set {
            this.mdnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class setContractEMailResponse {
    
    private response responseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class setContractEMail {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string userIDField;
    
    private string contractIDField;
    
    private string mdnField;
    
    private string minField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractID {
        get {
            return this.contractIDField;
        }
        set {
            this.contractIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mdn {
        get {
            return this.mdnField;
        }
        set {
            this.mdnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class memberResetPasswordResponse {
    
    private response returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class memberResetPassword {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string memberIDField;
    
    private string personIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string memberID {
        get {
            return this.memberIDField;
        }
        set {
            this.memberIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string personID {
        get {
            return this.personIDField;
        }
        set {
            this.personIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class memberChangePasswordResponse {
    
    private response returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class memberChangePassword {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string memberIDField;
    
    private string oldPasswordField;
    
    private string newPasswordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string memberID {
        get {
            return this.memberIDField;
        }
        set {
            this.memberIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string oldPassword {
        get {
            return this.oldPasswordField;
        }
        set {
            this.oldPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string newPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class memberChangeAccountResponse {
    
    private response returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class memberChangeAccount {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string oldAccountIDField;
    
    private string personIDField;
    
    private string newAccountIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string oldAccountID {
        get {
            return this.oldAccountIDField;
        }
        set {
            this.oldAccountIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string personID {
        get {
            return this.personIDField;
        }
        set {
            this.personIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string newAccountID {
        get {
            return this.newAccountIDField;
        }
        set {
            this.newAccountIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class getUserProfileResponse {
    
    private response responseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class getUserProfile {
    
    private string serviceIDField;
    
    private string servicePWDField;
    
    private string userIDField;
    
    private string contractIDField;
    
    private string mdnField;
    
    private string minField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serviceID {
        get {
            return this.serviceIDField;
        }
        set {
            this.serviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicePWD {
        get {
            return this.servicePWDField;
        }
        set {
            this.servicePWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractID {
        get {
            return this.contractIDField;
        }
        set {
            this.contractIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mdn {
        get {
            return this.mdnField;
        }
        set {
            this.mdnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class terminateProfile {
    
    private bool duplicateField;
    
    private profile profileField;
    
    private System.DateTime recordDateField;
    
    private bool recordDateFieldSpecified;
    
    private string terminateTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool duplicate {
        get {
            return this.duplicateField;
        }
        set {
            this.duplicateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public profile profile {
        get {
            return this.profileField;
        }
        set {
            this.profileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime recordDate {
        get {
            return this.recordDateField;
        }
        set {
            this.recordDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool recordDateSpecified {
        get {
            return this.recordDateFieldSpecified;
        }
        set {
            this.recordDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string terminateType {
        get {
            return this.terminateTypeField;
        }
        set {
            this.terminateTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class terminateResponse {
    
    private string descriptionField;
    
    private string resultCodeField;
    
    private terminateProfile terminateprofileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string resultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public terminateProfile terminateprofile {
        get {
            return this.terminateprofileField;
        }
        set {
            this.terminateprofileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aptg.com.tw/ws/api/core/ProfileService")]
public partial class getTerminateProfileResponse {
    
    private terminateResponse terminateResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public terminateResponse terminateResponse {
        get {
            return this.terminateResponseField;
        }
        set {
            this.terminateResponseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getTerminateProfileCompletedEventHandler(object sender, getTerminateProfileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTerminateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTerminateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public getTerminateProfileResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((getTerminateProfileResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getUserProfileCompletedEventHandler(object sender, getUserProfileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public getUserProfileResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((getUserProfileResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void memberChangeAccountCompletedEventHandler(object sender, memberChangeAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class memberChangeAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal memberChangeAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public memberChangeAccountResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((memberChangeAccountResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void memberChangePasswordCompletedEventHandler(object sender, memberChangePasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class memberChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal memberChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public memberChangePasswordResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((memberChangePasswordResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void memberResetPasswordCompletedEventHandler(object sender, memberResetPasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class memberResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal memberResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public memberResetPasswordResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((memberResetPasswordResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void setContractEMailCompletedEventHandler(object sender, setContractEMailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class setContractEMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal setContractEMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public setContractEMailResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((setContractEMailResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void setReadAgreementCompletedEventHandler(object sender, setReadAgreementCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class setReadAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal setReadAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public setReadAgreementResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((setReadAgreementResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void subscriberChangePasswordCompletedEventHandler(object sender, subscriberChangePasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class subscriberChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal subscriberChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public subscriberChangePasswordResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((subscriberChangePasswordResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void subscriberResetPasswordCompletedEventHandler(object sender, subscriberResetPasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class subscriberResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal subscriberResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public subscriberResetPasswordResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((subscriberResetPasswordResponse)(this.results[0]));
        }
    }
}
