//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3623
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsmDatabaseObjects {
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class TBSM_PURCHASE : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private string m_SRC_NO;
        
        private System.DateTime m_PURCHASE_DATE;
        
        private bool m_PURCHASE_DATEIsNull;
        
        private string m_SERIAL_ID;
        
        private string m_PAY_TYPE;
        
        private string m_SRC_CODE;
        
        private string m_CARD_EXPIRY;
        
        private string m_CVC2;
        
        private string m_MAS_NO;
        
        private decimal m_PK_NO;
        
        private bool m_PK_NOIsNull;
        
        private string m_APPROVAL_CODE;
        
        private string m_SRC_DATE;
        
        private System.DateTime m_MAS_DATE;
        
        private bool m_MAS_DATEIsNull;
        
        private decimal m_SERIAL_NO;
        
        private bool m_SERIAL_NOIsNull;
        
        private TBSM_PURCHASE_DTLS m_DETAILS;
        
        private string m_MAS_CODE;
        
        private string m_CARD_TYPE;
        
        private string m_CARD_NO;
        
        private string m_STATUS_FLG;
        
        public TBSM_PURCHASE() {
            // TODO : Add code to initialise the object
            this.m_PURCHASE_DATEIsNull = true;
            this.m_PK_NOIsNull = true;
            this.m_MAS_DATEIsNull = true;
            this.m_SERIAL_NOIsNull = true;
        }
        
        public TBSM_PURCHASE(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static TBSM_PURCHASE Null {
            get {
                TBSM_PURCHASE obj = new TBSM_PURCHASE();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("SRC_NO")]
        public string SRC_NO {
            get {
                return this.m_SRC_NO;
            }
            set {
                this.m_SRC_NO = value;
            }
        }
        
        [OracleObjectMappingAttribute("PURCHASE_DATE")]
        public System.DateTime PURCHASE_DATE {
            get {
                return this.m_PURCHASE_DATE;
            }
            set {
                this.m_PURCHASE_DATE = value;
            }
        }
        
        public bool PURCHASE_DATEIsNull {
            get {
                return this.m_PURCHASE_DATEIsNull;
            }
            set {
                this.m_PURCHASE_DATEIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("SERIAL_ID")]
        public string SERIAL_ID {
            get {
                return this.m_SERIAL_ID;
            }
            set {
                this.m_SERIAL_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("PAY_TYPE")]
        public string PAY_TYPE {
            get {
                return this.m_PAY_TYPE;
            }
            set {
                this.m_PAY_TYPE = value;
            }
        }
        
        [OracleObjectMappingAttribute("SRC_CODE")]
        public string SRC_CODE {
            get {
                return this.m_SRC_CODE;
            }
            set {
                this.m_SRC_CODE = value;
            }
        }
        
        [OracleObjectMappingAttribute("CARD_EXPIRY")]
        public string CARD_EXPIRY {
            get {
                return this.m_CARD_EXPIRY;
            }
            set {
                this.m_CARD_EXPIRY = value;
            }
        }
        
        [OracleObjectMappingAttribute("CVC2")]
        public string CVC2 {
            get {
                return this.m_CVC2;
            }
            set {
                this.m_CVC2 = value;
            }
        }
        
        [OracleObjectMappingAttribute("MAS_NO")]
        public string MAS_NO {
            get {
                return this.m_MAS_NO;
            }
            set {
                this.m_MAS_NO = value;
            }
        }
        
        [OracleObjectMappingAttribute("PK_NO")]
        public decimal PK_NO {
            get {
                return this.m_PK_NO;
            }
            set {
                this.m_PK_NO = value;
            }
        }
        
        public bool PK_NOIsNull {
            get {
                return this.m_PK_NOIsNull;
            }
            set {
                this.m_PK_NOIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("APPROVAL_CODE")]
        public string APPROVAL_CODE {
            get {
                return this.m_APPROVAL_CODE;
            }
            set {
                this.m_APPROVAL_CODE = value;
            }
        }
        
        [OracleObjectMappingAttribute("SRC_DATE")]
        public string SRC_DATE {
            get {
                return this.m_SRC_DATE;
            }
            set {
                this.m_SRC_DATE = value;
            }
        }
        
        [OracleObjectMappingAttribute("MAS_DATE")]
        public System.DateTime MAS_DATE {
            get {
                return this.m_MAS_DATE;
            }
            set {
                this.m_MAS_DATE = value;
            }
        }
        
        public bool MAS_DATEIsNull {
            get {
                return this.m_MAS_DATEIsNull;
            }
            set {
                this.m_MAS_DATEIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("SERIAL_NO")]
        public decimal SERIAL_NO {
            get {
                return this.m_SERIAL_NO;
            }
            set {
                this.m_SERIAL_NO = value;
            }
        }
        
        public bool SERIAL_NOIsNull {
            get {
                return this.m_SERIAL_NOIsNull;
            }
            set {
                this.m_SERIAL_NOIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("DETAILS")]
        public TBSM_PURCHASE_DTLS DETAILS {
            get {
                return this.m_DETAILS;
            }
            set {
                this.m_DETAILS = value;
            }
        }
        
        [OracleObjectMappingAttribute("MAS_CODE")]
        public string MAS_CODE {
            get {
                return this.m_MAS_CODE;
            }
            set {
                this.m_MAS_CODE = value;
            }
        }
        
        [OracleObjectMappingAttribute("CARD_TYPE")]
        public string CARD_TYPE {
            get {
                return this.m_CARD_TYPE;
            }
            set {
                this.m_CARD_TYPE = value;
            }
        }
        
        [OracleObjectMappingAttribute("CARD_NO")]
        public string CARD_NO {
            get {
                return this.m_CARD_NO;
            }
            set {
                this.m_CARD_NO = value;
            }
        }
        
        [OracleObjectMappingAttribute("STATUS_FLG")]
        public string STATUS_FLG {
            get {
                return this.m_STATUS_FLG;
            }
            set {
                this.m_STATUS_FLG = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SRC_NO", this.SRC_NO);
            if ((PURCHASE_DATEIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PURCHASE_DATE", this.PURCHASE_DATE);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SERIAL_ID", this.SERIAL_ID);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PAY_TYPE", this.PAY_TYPE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SRC_CODE", this.SRC_CODE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CARD_EXPIRY", this.CARD_EXPIRY);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CVC2", this.CVC2);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MAS_NO", this.MAS_NO);
            if ((PK_NOIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PK_NO", this.PK_NO);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "APPROVAL_CODE", this.APPROVAL_CODE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SRC_DATE", this.SRC_DATE);
            if ((MAS_DATEIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MAS_DATE", this.MAS_DATE);
            }
            if ((SERIAL_NOIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SERIAL_NO", this.SERIAL_NO);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "DETAILS", this.DETAILS);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MAS_CODE", this.MAS_CODE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CARD_TYPE", this.CARD_TYPE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CARD_NO", this.CARD_NO);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "STATUS_FLG", this.STATUS_FLG);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.SRC_NO = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SRC_NO")));
            this.PURCHASE_DATEIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "PURCHASE_DATE");
            if ((PURCHASE_DATEIsNull == false)) {
                this.PURCHASE_DATE = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PURCHASE_DATE")));
            }
            this.SERIAL_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SERIAL_ID")));
            this.PAY_TYPE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PAY_TYPE")));
            this.SRC_CODE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SRC_CODE")));
            this.CARD_EXPIRY = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CARD_EXPIRY")));
            this.CVC2 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CVC2")));
            this.MAS_NO = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MAS_NO")));
            this.PK_NOIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "PK_NO");
            if ((PK_NOIsNull == false)) {
                this.PK_NO = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PK_NO")));
            }
            this.APPROVAL_CODE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "APPROVAL_CODE")));
            this.SRC_DATE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SRC_DATE")));
            this.MAS_DATEIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MAS_DATE");
            if ((MAS_DATEIsNull == false)) {
                this.MAS_DATE = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MAS_DATE")));
            }
            this.SERIAL_NOIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "SERIAL_NO");
            if ((SERIAL_NOIsNull == false)) {
                this.SERIAL_NO = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SERIAL_NO")));
            }
            this.DETAILS = ((TBSM_PURCHASE_DTLS)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "DETAILS")));
            this.MAS_CODE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MAS_CODE")));
            this.CARD_TYPE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CARD_TYPE")));
            this.CARD_NO = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CARD_NO")));
            this.STATUS_FLG = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "STATUS_FLG")));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static TBSM_PURCHASE Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new TBSM_PURCHASE();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("TBSM_PURCHASE")]
    public class TBSM_PURCHASEFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            TBSM_PURCHASE obj = new TBSM_PURCHASE();
            return obj;
        }
    }
}
