//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3623
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsmDatabaseObjects {
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class TBSM_PURCHASE_DTL : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private string m_ASSET_ID;
        
        private System.DateTime m_START_DATE;
        
        private bool m_START_DATEIsNull;
        
        private string m_ITEM_ID;
        
        private string m_PACKAGE_NAME;
        
        private decimal m_AMOUNT;
        
        private bool m_AMOUNTIsNull;
        
        private decimal m_ITEM_NO;
        
        private bool m_ITEM_NOIsNull;
        
        private string m_ITEM_NAME;
        
        private string m_OFFER_ID;
        
        private decimal m_DURATION;
        
        private bool m_DURATIONIsNull;
        
        private string m_PACKAGE_ID;
        
        private decimal m_PK_NO;
        
        private bool m_PK_NOIsNull;
        
        private decimal m_QUOTA;
        
        private bool m_QUOTAIsNull;
        
        public TBSM_PURCHASE_DTL() {
            // TODO : Add code to initialise the object
            this.m_START_DATEIsNull = true;
            this.m_AMOUNTIsNull = true;
            this.m_ITEM_NOIsNull = true;
            this.m_DURATIONIsNull = true;
            this.m_PK_NOIsNull = true;
            this.m_QUOTAIsNull = true;
        }
        
        public TBSM_PURCHASE_DTL(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static TBSM_PURCHASE_DTL Null {
            get {
                TBSM_PURCHASE_DTL obj = new TBSM_PURCHASE_DTL();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("ASSET_ID")]
        public string ASSET_ID {
            get {
                return this.m_ASSET_ID;
            }
            set {
                this.m_ASSET_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("START_DATE")]
        public System.DateTime START_DATE {
            get {
                return this.m_START_DATE;
            }
            set {
                this.m_START_DATE = value;
            }
        }
        
        public bool START_DATEIsNull {
            get {
                return this.m_START_DATEIsNull;
            }
            set {
                this.m_START_DATEIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ITEM_ID")]
        public string ITEM_ID {
            get {
                return this.m_ITEM_ID;
            }
            set {
                this.m_ITEM_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("PACKAGE_NAME")]
        public string PACKAGE_NAME {
            get {
                return this.m_PACKAGE_NAME;
            }
            set {
                this.m_PACKAGE_NAME = value;
            }
        }
        
        [OracleObjectMappingAttribute("AMOUNT")]
        public decimal AMOUNT {
            get {
                return this.m_AMOUNT;
            }
            set {
                this.m_AMOUNT = value;
            }
        }
        
        public bool AMOUNTIsNull {
            get {
                return this.m_AMOUNTIsNull;
            }
            set {
                this.m_AMOUNTIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ITEM_NO")]
        public decimal ITEM_NO {
            get {
                return this.m_ITEM_NO;
            }
            set {
                this.m_ITEM_NO = value;
            }
        }
        
        public bool ITEM_NOIsNull {
            get {
                return this.m_ITEM_NOIsNull;
            }
            set {
                this.m_ITEM_NOIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ITEM_NAME")]
        public string ITEM_NAME {
            get {
                return this.m_ITEM_NAME;
            }
            set {
                this.m_ITEM_NAME = value;
            }
        }
        
        [OracleObjectMappingAttribute("OFFER_ID")]
        public string OFFER_ID {
            get {
                return this.m_OFFER_ID;
            }
            set {
                this.m_OFFER_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("DURATION")]
        public decimal DURATION {
            get {
                return this.m_DURATION;
            }
            set {
                this.m_DURATION = value;
            }
        }
        
        public bool DURATIONIsNull {
            get {
                return this.m_DURATIONIsNull;
            }
            set {
                this.m_DURATIONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("PACKAGE_ID")]
        public string PACKAGE_ID {
            get {
                return this.m_PACKAGE_ID;
            }
            set {
                this.m_PACKAGE_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("PK_NO")]
        public decimal PK_NO {
            get {
                return this.m_PK_NO;
            }
            set {
                this.m_PK_NO = value;
            }
        }
        
        public bool PK_NOIsNull {
            get {
                return this.m_PK_NOIsNull;
            }
            set {
                this.m_PK_NOIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("QUOTA")]
        public decimal QUOTA {
            get {
                return this.m_QUOTA;
            }
            set {
                this.m_QUOTA = value;
            }
        }
        
        public bool QUOTAIsNull {
            get {
                return this.m_QUOTAIsNull;
            }
            set {
                this.m_QUOTAIsNull = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ASSET_ID", this.ASSET_ID);
            if ((START_DATEIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "START_DATE", this.START_DATE);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ITEM_ID", this.ITEM_ID);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PACKAGE_NAME", this.PACKAGE_NAME);
            if ((AMOUNTIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "AMOUNT", this.AMOUNT);
            }
            if ((ITEM_NOIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ITEM_NO", this.ITEM_NO);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ITEM_NAME", this.ITEM_NAME);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OFFER_ID", this.OFFER_ID);
            if ((DURATIONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "DURATION", this.DURATION);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PACKAGE_ID", this.PACKAGE_ID);
            if ((PK_NOIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PK_NO", this.PK_NO);
            }
            if ((QUOTAIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "QUOTA", this.QUOTA);
            }
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.ASSET_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ASSET_ID")));
            this.START_DATEIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "START_DATE");
            if ((START_DATEIsNull == false)) {
                this.START_DATE = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "START_DATE")));
            }
            this.ITEM_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ITEM_ID")));
            this.PACKAGE_NAME = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PACKAGE_NAME")));
            this.AMOUNTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "AMOUNT");
            if ((AMOUNTIsNull == false)) {
                this.AMOUNT = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "AMOUNT")));
            }
            this.ITEM_NOIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ITEM_NO");
            if ((ITEM_NOIsNull == false)) {
                this.ITEM_NO = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ITEM_NO")));
            }
            this.ITEM_NAME = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ITEM_NAME")));
            this.OFFER_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OFFER_ID")));
            this.DURATIONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "DURATION");
            if ((DURATIONIsNull == false)) {
                this.DURATION = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "DURATION")));
            }
            this.PACKAGE_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PACKAGE_ID")));
            this.PK_NOIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "PK_NO");
            if ((PK_NOIsNull == false)) {
                this.PK_NO = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PK_NO")));
            }
            this.QUOTAIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "QUOTA");
            if ((QUOTAIsNull == false)) {
                this.QUOTA = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "QUOTA")));
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static TBSM_PURCHASE_DTL Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new TBSM_PURCHASE_DTL();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("TBSM_PURCHASE_DTL")]
    public class TBSM_PURCHASE_DTLFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            TBSM_PURCHASE_DTL obj = new TBSM_PURCHASE_DTL();
            return obj;
        }
    }
}
