//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3623
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsmDatabaseObjects {
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class TBSM_CLIENT_INFO : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private string m_OWNER_PHONE_STATUS;
        
        private string m_ACTIVATION_CODE;
        
        private string m_STATUS_FLG;
        
        private string m_OWNER_ID;
        
        private string m_OWNER_EMAIL;
        
        private decimal m_SERIAL_NO;
        
        private bool m_SERIAL_NOIsNull;
        
        private string m_OWNER_NAME;
        
        private string m_SERIAL_ID;
        
        private decimal m_REGION;
        
        private bool m_REGIONIsNull;
        
        private string m_OWNER_PHONE;
        
        private string m_DEFAULT_GROUP;
        
        private string m_MAC_ADDRESS;
        
        public TBSM_CLIENT_INFO() {
            // TODO : Add code to initialise the object
            this.m_SERIAL_NOIsNull = true;
            this.m_REGIONIsNull = true;
        }
        
        public TBSM_CLIENT_INFO(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static TBSM_CLIENT_INFO Null {
            get {
                TBSM_CLIENT_INFO obj = new TBSM_CLIENT_INFO();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("OWNER_PHONE_STATUS")]
        public string OWNER_PHONE_STATUS {
            get {
                return this.m_OWNER_PHONE_STATUS;
            }
            set {
                this.m_OWNER_PHONE_STATUS = value;
            }
        }
        
        [OracleObjectMappingAttribute("ACTIVATION_CODE")]
        public string ACTIVATION_CODE {
            get {
                return this.m_ACTIVATION_CODE;
            }
            set {
                this.m_ACTIVATION_CODE = value;
            }
        }
        
        [OracleObjectMappingAttribute("STATUS_FLG")]
        public string STATUS_FLG {
            get {
                return this.m_STATUS_FLG;
            }
            set {
                this.m_STATUS_FLG = value;
            }
        }
        
        [OracleObjectMappingAttribute("OWNER_ID")]
        public string OWNER_ID {
            get {
                return this.m_OWNER_ID;
            }
            set {
                this.m_OWNER_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("OWNER_EMAIL")]
        public string OWNER_EMAIL {
            get {
                return this.m_OWNER_EMAIL;
            }
            set {
                this.m_OWNER_EMAIL = value;
            }
        }
        
        [OracleObjectMappingAttribute("SERIAL_NO")]
        public decimal SERIAL_NO {
            get {
                return this.m_SERIAL_NO;
            }
            set {
                this.m_SERIAL_NO = value;
            }
        }
        
        public bool SERIAL_NOIsNull {
            get {
                return this.m_SERIAL_NOIsNull;
            }
            set {
                this.m_SERIAL_NOIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("OWNER_NAME")]
        public string OWNER_NAME {
            get {
                return this.m_OWNER_NAME;
            }
            set {
                this.m_OWNER_NAME = value;
            }
        }
        
        [OracleObjectMappingAttribute("SERIAL_ID")]
        public string SERIAL_ID {
            get {
                return this.m_SERIAL_ID;
            }
            set {
                this.m_SERIAL_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("REGION")]
        public decimal REGION {
            get {
                return this.m_REGION;
            }
            set {
                this.m_REGION = value;
            }
        }
        
        public bool REGIONIsNull {
            get {
                return this.m_REGIONIsNull;
            }
            set {
                this.m_REGIONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("OWNER_PHONE")]
        public string OWNER_PHONE {
            get {
                return this.m_OWNER_PHONE;
            }
            set {
                this.m_OWNER_PHONE = value;
            }
        }
        
        [OracleObjectMappingAttribute("DEFAULT_GROUP")]
        public string DEFAULT_GROUP {
            get {
                return this.m_DEFAULT_GROUP;
            }
            set {
                this.m_DEFAULT_GROUP = value;
            }
        }
        
        [OracleObjectMappingAttribute("MAC_ADDRESS")]
        public string MAC_ADDRESS {
            get {
                return this.m_MAC_ADDRESS;
            }
            set {
                this.m_MAC_ADDRESS = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OWNER_PHONE_STATUS", this.OWNER_PHONE_STATUS);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ACTIVATION_CODE", this.ACTIVATION_CODE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "STATUS_FLG", this.STATUS_FLG);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OWNER_ID", this.OWNER_ID);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OWNER_EMAIL", this.OWNER_EMAIL);
            if ((SERIAL_NOIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SERIAL_NO", this.SERIAL_NO);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OWNER_NAME", this.OWNER_NAME);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SERIAL_ID", this.SERIAL_ID);
            if ((REGIONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "REGION", this.REGION);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OWNER_PHONE", this.OWNER_PHONE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "DEFAULT_GROUP", this.DEFAULT_GROUP);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MAC_ADDRESS", this.MAC_ADDRESS);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.OWNER_PHONE_STATUS = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OWNER_PHONE_STATUS")));
            this.ACTIVATION_CODE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ACTIVATION_CODE")));
            this.STATUS_FLG = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "STATUS_FLG")));
            this.OWNER_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OWNER_ID")));
            this.OWNER_EMAIL = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OWNER_EMAIL")));
            this.SERIAL_NOIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "SERIAL_NO");
            if ((SERIAL_NOIsNull == false)) {
                this.SERIAL_NO = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SERIAL_NO")));
            }
            this.OWNER_NAME = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OWNER_NAME")));
            this.SERIAL_ID = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SERIAL_ID")));
            this.REGIONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "REGION");
            if ((REGIONIsNull == false)) {
                this.REGION = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "REGION")));
            }
            this.OWNER_PHONE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OWNER_PHONE")));
            this.DEFAULT_GROUP = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "DEFAULT_GROUP")));
            this.MAC_ADDRESS = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MAC_ADDRESS")));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static TBSM_CLIENT_INFO Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new TBSM_CLIENT_INFO();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("TBSM_CLIENT_INFO")]
    public class TBSM_CLIENT_INFOFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            TBSM_CLIENT_INFO obj = new TBSM_CLIENT_INFO();
            return obj;
        }
    }
}
