//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3623
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsmDatabaseObjects{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class TBSM_PURCHASE_DTLS : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private TBSM_PURCHASE_DTL[] m_TBSM_PURCHASE_DTL;
        
        public TBSM_PURCHASE_DTLS() {
            // TODO : Add code to initialise the object
        }
        
        public TBSM_PURCHASE_DTLS(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static TBSM_PURCHASE_DTLS Null {
            get {
                TBSM_PURCHASE_DTLS obj = new TBSM_PURCHASE_DTLS();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleArrayMappingAttribute()]
        public virtual TBSM_PURCHASE_DTL[] Value {
            get {
                return this.m_TBSM_PURCHASE_DTL;
            }
            set {
                this.m_TBSM_PURCHASE_DTL = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_TBSM_PURCHASE_DTL);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.m_TBSM_PURCHASE_DTL = ((TBSM_PURCHASE_DTL[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static TBSM_PURCHASE_DTLS Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new TBSM_PURCHASE_DTLS();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("TBSM_PURCHASE_DTLS")]
    public class TBSM_PURCHASE_DTLSFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            TBSM_PURCHASE_DTLS obj = new TBSM_PURCHASE_DTLS();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
            TBSM_PURCHASE_DTL[] collElem = new TBSM_PURCHASE_DTL[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }
}
